### ISSUE TITLE
The results is not satisfactory

### ISSUE THREAD

**Issue by Thea-wyj** [WindQingYang/MFPP#1]
![output](https://github.com/WindQingYang/MFPP/assets/66415651/8634771f-f576-4165-ad67-7b767cd21047)
![output2](https://github.com/WindQingYang/MFPP/assets/66415651/198a1b32-9bc0-4cf0-8edd-5dcbecf0d1c3)
Hello, I am a graduate student in China, and my research field is also the XAI. Recently, I read your paper of the method “MFPP”,  I want to apply it in my experiment. However, I cloned your code and tested it with example pictures, and found that my results are relatively different from those presented in your paper. I would like to ask if the default parameters in this code are inconsistent with your actual implementation. If so, could you please tell me what your parameter settings are like? Thank you very much!

`def mfpp(model,
         input,
         img_file,
         target=None,
         seed=0,
         num_masks=20000,
         resize_offset=2.0,
         layer=5,
         batch_size=32,
         p_1=0.5,
         resize_mode='bilinear'):`

**Comment by Thea-wyj** [comment]
![image](https://github.com/WindQingYang/MFPP/assets/66415651/ba352fca-dc92-4c13-9eb3-fa8b95a12414)
In addition, I noticed that the masks in mfpp method will be enlarged to 2.2 times of the original image and then cropped to the size of the original image, so the resulting saliency graph cannot completely overlap the features of the original image. I would like to know if you have encountered this problem. If so, I would like to ask you how to solve it, thank you!
![image](https://github.com/WindQingYang/MFPP/assets/66415651/8312d2c5-9233-459c-b229-72e475dc7777)

**Comment by WindQingYang** [comment]
> ![output](https://private-user-images.githubusercontent.com/66415651/313572962-8634771f-f576-4165-ad67-7b767cd21047.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMDg5MTksIm5iZiI6MTcxMjEwODYxOSwicGF0aCI6Ii82NjQxNTY1MS8zMTM1NzI5NjItODYzNDc3MWYtZjU3Ni00MTY1LWFkNjctN2I3NjdjZDIxMDQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDAxNDMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljYjU4NWFkMWI1YzAzMjA2NGE4ZGNhMjcyZmM1MmNmNjczOWVjMDczY2E5NjRiN2VkYzU0NWEyNmQxMDEyYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V1eD2Sw1KX3H9F5gleh1W9jJgq0MDGY2oW0DyVcJuxw) ![output2](https://private-user-images.githubusercontent.com/66415651/313573125-198a1b32-9bc0-4cf0-8edd-5dcbecf0d1c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMDg5MTksIm5iZiI6MTcxMjEwODYxOSwicGF0aCI6Ii82NjQxNTY1MS8zMTM1NzMxMjUtMTk4YTFiMzItOWJjMC00Y2YwLThlZGQtNWRjYmVjZjBkMWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDAxNDMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxM2QyNmQzNThiZGQzNWJhZGNkZDkwOGRmODk5NWI5MWU3ZWVkNTgzNTczYTkxNzM1N2I1ZmQzZDE4ZTUxY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ObUdz_ChvVweVl5MU7DFLY8utfDoYiV_ba8sv3Zodxc) Hello, I am a graduate student in China, and my research field is also the XAI. Recently, I read your paper of the method “MFPP”, I want to apply it in my experiment. However, I cloned your code and tested it with example pictures, and found that my results are relatively different from those presented in your paper. I would like to ask if the default parameters in this code are inconsistent with your actual implementation. If so, could you please tell me what your parameter settings are like? Thank you very much!
> 
> `def mfpp(model, input, img_file, target=None, seed=0, num_masks=20000, resize_offset=2.0, layer=5, batch_size=32, p_1=0.5, resize_mode='bilinear'):`


Hi, there, thanks for your interest in this work ^_^
The saliency map is strongly impacted by the classification results and backbone model (Resnet50 or VGG19 etc.). Secondly, the parameters also play a role in the result of granularity, but not the determining factor. you can tune the parameters to get a better result. The expeiments were done 5 years ago (2019), sorry we could not find the original experiment scripts code. You can just put the actual results as what it is, if you want to make a benchmark.

**Comment by WindQingYang** [comment]
> ![image](https://private-user-images.githubusercontent.com/66415651/315085671-ba352fca-dc92-4c13-9eb3-fa8b95a12414.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMTA0ODUsIm5iZiI6MTcxMjExMDE4NSwicGF0aCI6Ii82NjQxNTY1MS8zMTUwODU2NzEtYmEzNTJmY2EtZGM5Mi00YzEzLTllYjMtZmE4Yjk1YTEyNDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDAyMDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NzgwNmNmNmJlNDVhODIzNzRmN2ZkNTVlMzgwNDc1OTM2MzFiMzY5NTk1MDJlNTk4YmFmMjhlZmZjZGZjZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xFLKCOvN1coX-gvmPzdF0iso-PGldFK7fkakAUImP1U) In addition, I noticed that the masks in mfpp method will be enlarged to 2.2 times of the original image and then cropped to the size of the original image, so the resulting saliency graph cannot completely overlap the features of the original image. I would like to know if you have encountered this problem. If so, I would like to ask you how to solve it, thank you! ![image](https://private-user-images.githubusercontent.com/66415651/315104149-8312d2c5-9233-459c-b229-72e475dc7777.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMTA0ODUsIm5iZiI6MTcxMjExMDE4NSwicGF0aCI6Ii82NjQxNTY1MS8zMTUxMDQxNDktODMxMmQyYzUtOTIzMy00NTljLWIyMjktNzJlNDc1ZGM3Nzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDAyMDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NjVmNWQ2Mzk0ZDM2M2I4YmE2NGRhMDk0OTdhYzM5ZDIwMzZmYTY3MTFlYTU2YTU4MjM2YmJiOTQ1OTIyZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Io7YTT9yxY9Z851EAWjeakYzJQ1s1Lk_Z2L3BUV8RHo)

the scaled image was input of the tested model, and your purpose is to get the scores. and when you calculate the saliency map. you should original size masks weighted sum with the scores output from last step.

**Comment by Thea-wyj** [comment]
> > ![image](https://private-user-images.githubusercontent.com/66415651/315085671-ba352fca-dc92-4c13-9eb3-fa8b95a12414.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMTA0ODUsIm5iZiI6MTcxMjExMDE4NSwicGF0aCI6Ii82NjQxNTY1MS8zMTUwODU2NzEtYmEzNTJmY2EtZGM5Mi00YzEzLTllYjMtZmE4Yjk1YTEyNDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDAyMDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NzgwNmNmNmJlNDVhODIzNzRmN2ZkNTVlMzgwNDc1OTM2MzFiMzY5NTk1MDJlNTk4YmFmMjhlZmZjZGZjZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xFLKCOvN1coX-gvmPzdF0iso-PGldFK7fkakAUImP1U) In addition, I noticed that the masks in mfpp method will be enlarged to 2.2 times of the original image and then cropped to the size of the original image, so the resulting saliency graph cannot completely overlap the features of the original image. I would like to know if you have encountered this problem. If so, I would like to ask you how to solve it, thank you! ![image](https://private-user-images.githubusercontent.com/66415651/315104149-8312d2c5-9233-459c-b229-72e475dc7777.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMTA0ODUsIm5iZiI6MTcxMjExMDE4NSwicGF0aCI6Ii82NjQxNTY1MS8zMTUxMDQxNDktODMxMmQyYzUtOTIzMy00NTljLWIyMjktNzJlNDc1ZGM3Nzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDAyMDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NjVmNWQ2Mzk0ZDM2M2I4YmE2NGRhMDk0OTdhYzM5ZDIwMzZmYTY3MTFlYTU2YTU4MjM2YmJiOTQ1OTIyZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Io7YTT9yxY9Z851EAWjeakYzJQ1s1Lk_Z2L3BUV8RHo)
> 
> the scaled image was input of the tested model, and your purpose is to get the scores. and when you calculate the saliency map. you should original size masks weighted sum with the scores output from last step.

I got it. Thank you for your answer!

**Comment by WindQingYang** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/66415651/315085671-ba352fca-dc92-4c13-9eb3-fa8b95a12414.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMTA0ODUsIm5iZiI6MTcxMjExMDE4NSwicGF0aCI6Ii82NjQxNTY1MS8zMTUwODU2NzEtYmEzNTJmY2EtZGM5Mi00YzEzLTllYjMtZmE4Yjk1YTEyNDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDAyMDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NzgwNmNmNmJlNDVhODIzNzRmN2ZkNTVlMzgwNDc1OTM2MzFiMzY5NTk1MDJlNTk4YmFmMjhlZmZjZGZjZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xFLKCOvN1coX-gvmPzdF0iso-PGldFK7fkakAUImP1U) In addition, I noticed that the masks in mfpp method will be enlarged to 2.2 times of the original image and then cropped to the size of the original image, so the resulting saliency graph cannot completely overlap the features of the original image. I would like to know if you have encountered this problem. If so, I would like to ask you how to solve it, thank you! ![image](https://private-user-images.githubusercontent.com/66415651/315104149-8312d2c5-9233-459c-b229-72e475dc7777.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMTA0ODUsIm5iZiI6MTcxMjExMDE4NSwicGF0aCI6Ii82NjQxNTY1MS8zMTUxMDQxNDktODMxMmQyYzUtOTIzMy00NTljLWIyMjktNzJlNDc1ZGM3Nzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDAyMDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NjVmNWQ2Mzk0ZDM2M2I4YmE2NGRhMDk0OTdhYzM5ZDIwMzZmYTY3MTFlYTU2YTU4MjM2YmJiOTQ1OTIyZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Io7YTT9yxY9Z851EAWjeakYzJQ1s1Lk_Z2L3BUV8RHo)
> > 
> > 
> > the scaled image was input of the tested model, and your purpose is to get the scores. and when you calculate the saliency map. you should original size masks weighted sum with the scores output from last step.
> 
> I got it. Thank you for your answer!

You are very welcome! I will close this issue.
Feel free to raise new issue if you need any further support.
